### ISSUE TITLE
Barebones web platform

### ISSUE THREAD

**Issue by durasj** [durasj/chipsandcode#1]
Simple web platform accessible from all major devices without any setup, including Chromebooks, tablets, and smartphones. 

- [x] Lightweight prerendered Single Page Application with:
  - [x] Homepage - simple call-to-action for Learn and Experiment
  - [x] Learn page - empty, ready for Markdown content
  - [x] Experiment - one item for each tool
  - [x] About
- [x] Sign in
- [x] Optimization for mobile devices
- [x] Minimal size and blazing fast loads with lazy loading - ideally using Svelte, Tailwind - tree-shaking and minification are given
- [x] CI/CD using Cloudflare Pages
- [x] Deployed at www.chipsandcode.com
