### ISSUE TITLE
Hardware Simulator with Editor - Hardware IDE

### ISSUE THREAD

**Issue by durasj** [durasj/chipsandcode#2]
Reimagined Nand2Tetris Hardware Simulator.

- [x] HDL Language
- [x] Code editor with syntax highlighting for HDL
- [x] Real-time interpretation of HDL
- [x] Input/Internal/Output pins state
- [x] Testing Scripts
- [x] Save state
- [x] Share
- [x] Full-screen
