### ISSUE TITLE
Content management

### ISSUE THREAD

**Issue by durasj** [durasj/chipsandcode#5]
Learn page powered by versioned .md files.

- [x] Compilation of markdown in Svelte.
- [x] Dynamic page generation.
- [x] Markdown metadata.
- [x] Typography.
- [x] Inline tool embedding.
